#  _______   ___  ___  ___       ________
# |\  ___ \ |\  \|\  \|\  \     |\   __  \
# \ \   __/|\ \  \\\  \ \  \    \ \  \|\  \
#  \ \  \_|/_\ \  \\\  \ \  \    \ \   __  \
#   \ \  \_|\ \ \  \\\  \ \  \____\ \  \ \  \
#    \ \_______\ \_______\ \_______\ \__\ \__\
#     \|_______|\|_______|\|_______|\|__|\|__|
monsters:
  elder_guardian: 40
  wither_skeleton: 100
  stray: 20
  husk: 15
  zombie_villager: 15
  skeleton_horse: 30
  zombie_horse: 50
  evoker_fangs: 40
  evoker: 40
  vex: 20
  vindicator: 40
  illusioner: 50
  creeper: 40
  skeleton: 10
  spider: 15
  giant: 200
  zombie: 10
  slime: 5
  ghast: 50
  zombified_piglin: 25
  enderman: 40
  cave_spider: 15
  silverfish: 5
  blaze: 25
  ender_dragon: 7500
  magma_cube: 7
  wither: 5000
  witch: 30
  endermite: 5
  guardian: 20
  shulker: 50
  iron_golem: -30
  polar_bear: 10
  villager: -20
  phantom: 20
  drowned: 10
  pillager: 20
  ravager: 70
  trader_llama: -20
  wandering_trader: -40
  hoglin: 60
  piglin: 20
  zoglin: 80
  piglin_brute: 200
events:
  bloodmoon:
    bloodmoon_giant: 2000
    bloodmoon_zombie: 300
    bloodmoon_skeleton: 200
  nether_raid:
    piglin_brute_raider: 1500
    wither_skeleton_guard: 500
    piglin_raider: 300
    piglin_thief: 100
    blaze_raider: 200
    zombie_piglin_minion: 75
  end_pirates:
    enderman_pirate_captain: 1500
    enderman_gunner: 750
    enderman_pirate: 300
